[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v 
markers =
    cas2_only: test réservé au cas2 uniquement (représentation transaction)


